# Generated by Django 5.2.5 on 2026-02-19 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expertprofilesettings',
            options={'verbose_name_plural': 'Expert Profile Settings'},
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='expert/cover_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='expertise_areas',
            field=models.TextField(blank=True, help_text='Comma separated areas of expertise'),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='is_profile_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='phone_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list, help_text='List of phone numbers with type'),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='professional_title',
            field=models.CharField(blank=True, help_text='e.g., Clinical Psychologist, Licensed Therapist', max_length=200),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='expert/profile_photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='session_duration',
            field=models.IntegerField(default=60, help_text='Session duration in minutes'),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='show_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='expertprofilesettings',
            name='specializations',
            field=models.TextField(blank=True, help_text='Comma separated specializations'),
        ),
        migrations.AlterField(
            model_name='expertprofilesettings',
            name='languages',
            field=models.CharField(blank=True, help_text='Comma separated languages (e.g., English, Spanish, French)', max_length=500),
        ),
        migrations.AlterField(
            model_name='expertprofilesettings',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Enter each qualification on a new line'),
        ),
    ]
