# Generated by Django 5.2.5 on 2026-02-23 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0002_alter_expertprofilesettings_options_and_more'),
        ('user', '0006_remove_chatqueue_energy_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payout',
            name='therapist',
        ),
        migrations.AlterModelOptions(
            name='timeoff',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Time Off'},
        ),
        migrations.RemoveField(
            model_name='timeoff',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='timeoff',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('session_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meeting_link', models.URLField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seeker_bookings', to=settings.AUTH_USER_MODEL)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user.therapist')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='TherapistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('advance_booking_days', models.IntegerField(default=30, help_text='How far in advance clients can book')),
                ('session_duration', models.IntegerField(default=90, help_text='Default session duration in minutes')),
                ('buffer_time', models.IntegerField(default=15, help_text='Buffer time between sessions in minutes')),
                ('video_enabled', models.BooleanField(default=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('instant_booking', models.BooleanField(default=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='user.therapist')),
            ],
            options={
                'verbose_name_plural': 'Therapist Settings',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=90)),
                ('is_available', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_slots', to='expert.availability')),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='expert.booking')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='user.therapist')),
            ],
            options={
                'verbose_name_plural': 'Time Slots',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_detail', to='expert.timeslot'),
        ),
        migrations.DeleteModel(
            name='Earning',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['therapist', 'date', 'is_available'], name='expert_time_therapi_7d6888_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['therapist', 'date', 'is_booked'], name='expert_time_therapi_e1abc6_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'is_available'], name='expert_time_date_0b8288_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('therapist', 'date', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['therapist', 'session_date'], name='expert_book_therapi_825324_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['seeker', 'status'], name='expert_book_seeker__784478_idx'),
        ),
    ]
