# Generated by Django 5.2.5 on 2026-02-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0003_remove_payout_therapist_alter_timeoff_options_and_more'),
        ('user', '0006_remove_chatqueue_energy_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='user.sessionbooking'),
        ),
    ]
