# Generated by Django 5.2.5 on 2026-03-03 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0004_alter_timeslot_booking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_admin_reply', models.BooleanField(default=False, help_text='True if expert replied')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sender', 'recipient', 'timestamp'], name='expert_chat_sender__355d55_idx'), models.Index(fields=['recipient', 'is_read'], name='expert_chat_recipie_c92850_idx')],
            },
        ),
    ]
