# Generated by Django 5.2.5 on 2026-03-09 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert', '0005_chatmessage'),
        ('user', '0013_alter_sessionbooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('prescription', 'Prescription'), ('recommendation', 'Recommendation'), ('exercise', 'Exercise/Homework'), ('referral', 'Referral'), ('follow_up', 'Follow-up Note'), ('general', 'General Note')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('medication_name', models.CharField(blank=True, max_length=200, null=True)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('exercise_name', models.CharField(blank=True, max_length=200, null=True)),
                ('exercise_instructions', models.TextField(blank=True, null=True)),
                ('exercise_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='session_notes/%Y/%m/')),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_notes', to='user.sessionbooking')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_notes', to='user.therapist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_session_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='expert_sess_session_6d399f_idx'), models.Index(fields=['user', 'is_read'], name='expert_sess_user_id_24d57a_idx')],
            },
        ),
    ]
