# Generated by Django 5.2.5 on 2026-03-10 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_blocked_at_user_blocked_by_user_blocked_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertSupportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_admin_reply', models.BooleanField(default=False, help_text='True if admin replied')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_support_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_support_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['sender', 'recipient', 'timestamp'], name='accounts_ex_sender__cad8f5_idx'), models.Index(fields=['recipient', 'is_read'], name='accounts_ex_recipie_72896d_idx')],
            },
        ),
    ]
