# Generated by Django 5.2.5 on 2026-03-10 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_expertsupportchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_type', models.CharField(choices=[('user', 'User'), ('expert', 'Expert')], max_length=10)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=False, help_text='Admin approval for display')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Platform Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
