# Generated by Django 5.2.5 on 2026-02-17 08:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('energy', 'Energy Level'), ('mood', 'Core Mood'), ('stress', 'Stress/Anxiety'), ('focus', 'Focus/Motivation'), ('social', 'Social Connection')], default='mood', max_length=50)),
                ('weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(3.0)])),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mood', models.CharField(choices=[('low', 'Low'), ('stressed', 'Stressed'), ('calm', 'Calm'), ('motivated', 'Motivated'), ('anxious', 'Anxious')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fas fa-video', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🌱', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood_user1', models.CharField(max_length=50)),
                ('mood_user2', models.CharField(blank=True, max_length=50, null=True)),
                ('alias_user1', models.CharField(max_length=50)),
                ('alias_user2', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='searching', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ended_chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='user.anonymouschatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('harassment', 'Harassment'), ('spam', 'Spam'), ('inappropriate', 'Inappropriate content'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='user.chatmessage')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_reports_received', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_reviewed', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='user.anonymouschatroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_mood', models.CharField(choices=[('low', 'Low/Depressed'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed'), ('motivated', 'Motivated/Energetic'), ('anxious', 'Anxious/Worried'), ('neutral', 'Neutral/Balanced'), ('irritable', 'Irritable/Frustrated')], max_length=20)),
                ('secondary_mood', models.CharField(blank=True, choices=[('low', 'Low/Depressed'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed'), ('motivated', 'Motivated/Energetic'), ('anxious', 'Anxious/Worried'), ('neutral', 'Neutral/Balanced'), ('irritable', 'Irritable/Frustrated')], max_length=20, null=True)),
                ('intensity_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.CharField(blank=True, choices=[('low', 'Low Energy'), ('medium', 'Medium Energy'), ('high', 'High Energy')], default='medium', help_text='Energy level derived from mood analysis', max_length=20, null=True)),
                ('mood_profile', models.JSONField(blank=True, default=dict, help_text='Stores mood analysis patterns and profiles', null=True)),
                ('notes', models.TextField(blank=True, help_text="Optional personal notes about how you're feeling", null=True)),
                ('final_mood', models.CharField(blank=True, choices=[('low', 'Low/Depressed'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed'), ('motivated', 'Motivated/Energetic'), ('anxious', 'Anxious/Worried'), ('neutral', 'Neutral/Balanced'), ('irritable', 'Irritable/Frustrated')], help_text='Legacy field - use primary_mood for new code', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('mood', models.CharField(choices=[('low', 'Low/Depressed'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed'), ('motivated', 'Motivated/Energetic'), ('anxious', 'Anxious/Worried'), ('neutral', 'Neutral/Balanced'), ('irritable', 'Irritable/Frustrated')], max_length=20)),
                ('intensity_score', models.IntegerField(default=1, help_text='Intensity of this emotion (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='user.emotionalquestion')),
            ],
        ),
        migrations.CreateModel(
            name='EmotionalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='user.emotionalcheckin')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.emotionaloption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.emotionalquestion')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('anxiety_level', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('exercise_minutes', models.IntegerField(blank=True, null=True)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AtomicTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mood', models.CharField(choices=[('low', 'Low/Depressed'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed'), ('motivated', 'Motivated/Energetic'), ('anxious', 'Anxious/Worried'), ('neutral', 'Neutral/Balanced'), ('irritable', 'Irritable/Frustrated')], max_length=20)),
                ('energy_level', models.CharField(choices=[('low', 'Low Energy'), ('medium', 'Medium Energy'), ('high', 'High Energy')], default='medium', max_length=20)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.taskcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='therapists/')),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0)),
                ('total_sessions', models.IntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='therapists', to='user.sessioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='SessionBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_sessions', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sessioncategory')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='user.therapist')),
            ],
            options={
                'ordering': ['booking_date', 'booking_time'],
            },
        ),
        migrations.CreateModel(
            name='UserTaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='user.emotionalcheckin')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.atomictask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeling_after', models.CharField(choices=[('much_better', 'Much better'), ('better', 'Better than before'), ('same', 'About the same'), ('worse', 'Still struggling')], max_length=20)),
                ('was_helpful', models.CharField(choices=[('yes', 'Yes, very helpful'), ('somewhat', 'Somewhat helpful'), ('no', 'No, not helpful')], default='yes', max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1-5', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='user.anonymouschatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('room', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'timestamp'], name='user_chatme_room_id_2f5c95_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'timestamp'], name='user_chatme_sender__71e26b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emotionalanswer',
            unique_together={('checkin', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='sessionbooking',
            unique_together={('therapist', 'booking_date', 'booking_time')},
        ),
    ]
