# Generated by Django 5.2.5 on 2026-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_atomictask_created_at_atomictask_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomictask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='atomictask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
