# Generated by Django 5.2.5 on 2026-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_atomictask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatqueue',
            name='energy_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='mood_profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
