# Generated by Django 5.2.5 on 2026-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_chatqueue_energy_level_chatqueue_mood_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfeedback',
            name='was_helpful',
            field=models.CharField(choices=[('yes', 'Yes, very helpful'), ('somewhat', 'Somewhat helpful'), ('no', 'No, not helpful')], max_length=10),
        ),
    ]
