# Generated by Django 5.2.5 on 2026-02-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_chatfeedback_was_helpful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatqueue',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='chatqueue',
            name='mood_profile',
        ),
        migrations.AlterField(
            model_name='chatfeedback',
            name='was_helpful',
            field=models.CharField(choices=[('yes', 'Yes, very helpful'), ('somewhat', 'Somewhat helpful'), ('no', 'No, not helpful')], default='yes', max_length=10),
        ),
    ]
