# Generated by Django 5.2.5 on 2026-02-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_chatqueue_energy_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatqueue',
            name='energy_level',
            field=models.CharField(choices=[('low', 'Low Energy'), ('medium', 'Medium Energy'), ('high', 'High Energy')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='intensity',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='mood_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatqueue',
            name='secondary_mood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
