# Generated by Django 5.2.5 on 2026-02-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_chatqueue_energy_level_chatqueue_intensity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('RPS', 'Rock Paper Scissors'), ('SUDOKU', 'Sudoku'), ('MEMORY', 'Memory Match')], max_length=10)),
                ('highest_score', models.IntegerField(default=0)),
                ('best_time', models.IntegerField(blank=True, null=True)),
                ('games_played', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'game')},
            },
        ),
    ]
