# Generated by Django 5.2.5 on 2026-03-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_gamescore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('RPS', 'Rock Paper Scissors'), ('SUDOKU', 'Sudoku'), ('MEMORY', 'Memory Match'), ('BREATHING', 'Color Breathing'), ('BUBBLEPOP', 'Bubble Pop'), ('COLORING', 'Mindful Coloring')], max_length=10),
        ),
    ]
