# Generated by Django 5.2.5 on 2026-03-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_gamescore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atomictask',
            name='mood',
            field=models.CharField(choices=[('low', 'Low/Depressed/Sad'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed/Peaceful'), ('motivated', 'Motivated/Energetic/Productive'), ('anxious', 'Anxious/Worried/Nervous'), ('neutral', 'Neutral/Balanced/Okay'), ('irritable', 'Irritable/Frustrated/Annoyed'), ('happy', 'Happy/Joyful/Content'), ('excited', 'Excited/Enthusiastic/Thrilled'), ('grateful', 'Grateful/Appreciative/Thankful'), ('hopeful', 'Hopeful/Optimistic/Positive'), ('lonely', 'Lonely/Isolated/Abandoned'), ('overwhelmed', 'Overwhelmed/Unable to cope'), ('peaceful', 'Peaceful/Serene/Tranquil'), ('energetic', 'Energetic/Lively/Vibrant'), ('tired', 'Tired/Exhausted/Drained'), ('confused', 'Confused/Uncertain/Lost'), ('hopeless', 'Hopeless/Despair/Discouraged'), ('loved', 'Loved/Cared for/Appreciated'), ('proud', 'Proud/Accomplished/Confident')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emotionalcheckin',
            name='final_mood',
            field=models.CharField(blank=True, choices=[('low', 'Low/Depressed/Sad'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed/Peaceful'), ('motivated', 'Motivated/Energetic/Productive'), ('anxious', 'Anxious/Worried/Nervous'), ('neutral', 'Neutral/Balanced/Okay'), ('irritable', 'Irritable/Frustrated/Annoyed'), ('happy', 'Happy/Joyful/Content'), ('excited', 'Excited/Enthusiastic/Thrilled'), ('grateful', 'Grateful/Appreciative/Thankful'), ('hopeful', 'Hopeful/Optimistic/Positive'), ('lonely', 'Lonely/Isolated/Abandoned'), ('overwhelmed', 'Overwhelmed/Unable to cope'), ('peaceful', 'Peaceful/Serene/Tranquil'), ('energetic', 'Energetic/Lively/Vibrant'), ('tired', 'Tired/Exhausted/Drained'), ('confused', 'Confused/Uncertain/Lost'), ('hopeless', 'Hopeless/Despair/Discouraged'), ('loved', 'Loved/Cared for/Appreciated'), ('proud', 'Proud/Accomplished/Confident')], help_text='Legacy field - use primary_mood for new code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emotionalcheckin',
            name='primary_mood',
            field=models.CharField(choices=[('low', 'Low/Depressed/Sad'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed/Peaceful'), ('motivated', 'Motivated/Energetic/Productive'), ('anxious', 'Anxious/Worried/Nervous'), ('neutral', 'Neutral/Balanced/Okay'), ('irritable', 'Irritable/Frustrated/Annoyed'), ('happy', 'Happy/Joyful/Content'), ('excited', 'Excited/Enthusiastic/Thrilled'), ('grateful', 'Grateful/Appreciative/Thankful'), ('hopeful', 'Hopeful/Optimistic/Positive'), ('lonely', 'Lonely/Isolated/Abandoned'), ('overwhelmed', 'Overwhelmed/Unable to cope'), ('peaceful', 'Peaceful/Serene/Tranquil'), ('energetic', 'Energetic/Lively/Vibrant'), ('tired', 'Tired/Exhausted/Drained'), ('confused', 'Confused/Uncertain/Lost'), ('hopeless', 'Hopeless/Despair/Discouraged'), ('loved', 'Loved/Cared for/Appreciated'), ('proud', 'Proud/Accomplished/Confident')], max_length=20),
        ),
        migrations.AlterField(
            model_name='emotionalcheckin',
            name='secondary_mood',
            field=models.CharField(blank=True, choices=[('low', 'Low/Depressed/Sad'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed/Peaceful'), ('motivated', 'Motivated/Energetic/Productive'), ('anxious', 'Anxious/Worried/Nervous'), ('neutral', 'Neutral/Balanced/Okay'), ('irritable', 'Irritable/Frustrated/Annoyed'), ('happy', 'Happy/Joyful/Content'), ('excited', 'Excited/Enthusiastic/Thrilled'), ('grateful', 'Grateful/Appreciative/Thankful'), ('hopeful', 'Hopeful/Optimistic/Positive'), ('lonely', 'Lonely/Isolated/Abandoned'), ('overwhelmed', 'Overwhelmed/Unable to cope'), ('peaceful', 'Peaceful/Serene/Tranquil'), ('energetic', 'Energetic/Lively/Vibrant'), ('tired', 'Tired/Exhausted/Drained'), ('confused', 'Confused/Uncertain/Lost'), ('hopeless', 'Hopeless/Despair/Discouraged'), ('loved', 'Loved/Cared for/Appreciated'), ('proud', 'Proud/Accomplished/Confident')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emotionaloption',
            name='mood',
            field=models.CharField(choices=[('low', 'Low/Depressed/Sad'), ('stressed', 'Stressed/Overwhelmed'), ('calm', 'Calm/Relaxed/Peaceful'), ('motivated', 'Motivated/Energetic/Productive'), ('anxious', 'Anxious/Worried/Nervous'), ('neutral', 'Neutral/Balanced/Okay'), ('irritable', 'Irritable/Frustrated/Annoyed'), ('happy', 'Happy/Joyful/Content'), ('excited', 'Excited/Enthusiastic/Thrilled'), ('grateful', 'Grateful/Appreciative/Thankful'), ('hopeful', 'Hopeful/Optimistic/Positive'), ('lonely', 'Lonely/Isolated/Abandoned'), ('overwhelmed', 'Overwhelmed/Unable to cope'), ('peaceful', 'Peaceful/Serene/Tranquil'), ('energetic', 'Energetic/Lively/Vibrant'), ('tired', 'Tired/Exhausted/Drained'), ('confused', 'Confused/Uncertain/Lost'), ('hopeless', 'Hopeless/Despair/Discouraged'), ('loved', 'Loved/Cared for/Appreciated'), ('proud', 'Proud/Accomplished/Confident')], max_length=20),
        ),
    ]
