# Generated by Django 5.2.5 on 2026-03-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_gamescore_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='game',
            field=models.CharField(choices=[('RPS', 'Rock Paper Scissors'), ('SUDOKU', 'Sudoku'), ('MEMORY', 'Memory Match'), ('BREATHING', 'Color Breathing'), ('BUBBLEPOP', 'Bubble Pop'), ('COLORING', 'Mindful Coloring'), ('ODDEVEN', 'Odd or Even'), ('SOS', 'SOS Game'), ('SNAKE', 'Snake Eating Balls')], max_length=10),
        ),
    ]
