# Generated by Django 5.2.5 on 2026-03-09 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_gamescore_game'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionbooking',
            options={'ordering': ['-booking_date', '-booking_time']},
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('expert', 'Expert'), ('admin', 'Admin'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='meeting_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='meeting_platform',
            field=models.CharField(choices=[('google_meet', 'Google Meet'), ('jitsi', 'Jitsi Meet'), ('zoom', 'Zoom'), ('custom', 'Custom Link')], default='jitsi', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='original_booking_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_sessions', to='user.sessionbooking'),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('free', 'Free Session')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='reschedule_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sessionbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['user', 'status'], name='user_sessio_user_id_4a7b29_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['therapist', 'status'], name='user_sessio_therapi_36b772_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['booking_date', 'status'], name='user_sessio_booking_06b566_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionbooking',
            index=models.Index(fields=['meeting_id'], name='user_sessio_meeting_32402c_idx'),
        ),
    ]
